FROM python:3.13

ENV PYTHONBUFFERED=1 \
    PYTHONDOWNWRITEBYTECODE=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY /app ./app

# port we are using
EXPOSE 8000 

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]