version: "3.9"

services:
  imu_83_joint1:
    image: smart-mfg-imu-imu:latest
    command: ["python3", "-m", "imu"]
    environment:
      DEVICE_ID: "83"
      AUTO_TARE: "true"
    volumes:
      - /home/admin/smart-mfg-imu/data:/app/data
      - /dev/i2c-1:/dev/i2c-1
      - /dev/gpiochip0:/dev/gpiochip0
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.device_id == 192.168.1.83